name: Publish package to pub.dev
on:
	pull_request:
		branches:   
			- master
jobs:
	build:
		runs-on: ubuntu-latest
		container:
			image:  google/dart:latest
		steps:
		- uses: actions/checkout@v1
		- name: Setup credentials
			run: | 
				mkdir -p ~/.pub-cache 
				cat <<EOF > ~/.pub-cache/credentials.json
				${{ secrets.CREDENTIALS }}
				EOF
		- name: Format code
			run: dartfmt -w lib
		- name: Publish package
			run: pub publish -f